services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/python:3
    env_file: ../.devcontainer/devcontainer.env
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity